### ISSUE TITLE
Accessing the connection in a publish function

### ISSUE THREAD

**Issue by pfuerholz** [lorensr/server-session#1]
Thanks for you lib. I think it is really useful. 
Unfortunately if I try to access the store with `Session.get(<key>)` in publish method I get following exception:

``` javascript
Exception from sub <my-publish-method> id HGYYFZZSqMr28zFJX TypeError: Cannot read property 'connection' of undefined
I20160731-15:24:16.969(2)?     at Object.store (packages/loren:server-session/server-session.js:7:15)
I20160731-15:24:16.969(2)?     at Object.get (packages/loren:server-session/server-session.js:17:12)
I20160731-15:24:16.969(2)?     at Subscription.getBillsPublication [as _handler] (server/publications.js:33:39)
I20160731-15:24:16.969(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160731-15:24:16.969(2)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20160731-15:24:16.970(2)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20160731-15:24:16.970(2)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20160731-15:24:16.970(2)?     at packages/ddp-server/livedata_server.js:551:43
```

(As I have read [here](https://github.com/meteor/meteor/issues/6369) there is some discussion about this topic.)
For my issue I was able to use (in Meteor 1.4) following workaround: Instead of calling `Session.get(<key>)` I use following code:

``` javascript
const conx = this.connection;
if (!conx['_server-session']) {
    conx['_server-session'] = {};
}
const value = conx['_server-session'][<key>];
```

According to [Meteor-API](http://docs.meteor.com/api/pubsub.html#Subscription-connection) `this.connection` should be a supported way for accessing the connection object. (I did not try to use `this.connection` in all cases...)

**Comment by lorensr** [comment]
Thanks! I guess `DDP._CurrentInvocation.get()` must return `undefined` inside publishers. We could add to the API like `Session.fromPublisher(this).get('my-key')`. Assuming that `this.connection` is the same as `this.connection` inside a Method.

**Comment by pfuerholz** [comment]
I would be happy with this solution!
